<Workspace Version="1.2.1.3083" X="0" Y="0" zoom="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="94f5065f-d47b-4896-8151-9fd0059f2c78" type="PythonNodeModels.PythonNode" nickname="Python Script" x="253" y="245" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import sys

sys.path += ['C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2017.1\helpers', 'C:\Program Files (x86)\IronPython 2.7\Lib']

import clr
clr.AddReference('ProtoGeometry')
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
clr.AddReference("RevitServices")
clr.AddReference("RevitNodes")

import generator3

path = 'C:\Users\gary\Desktop\ironpython-stubs'
generator3.quiet = False

modules = ['Autodesk.DesignScript.Geometry',
'Autodesk.DesignScript.Geometry.TSpline',

'Autodesk.Revit.ApplicationServices',
'Autodesk.Revit.Attributes',
'Autodesk.Revit.Creation',
'Autodesk.Revit.Exceptions',
'Autodesk.Revit.Utility',

'Autodesk.Revit.DB',
'Autodesk.Revit.DB.Analysis',
'Autodesk.Revit.DB.Architecture',
'Autodesk.Revit.DB.Electrical',
'Autodesk.Revit.DB.Events',
'Autodesk.Revit.DB.ExtensibleStorage',
'Autodesk.Revit.DB.ExternalService',
'Autodesk.Revit.DB.Fabrication',
'Autodesk.Revit.DB.IFC',
'Autodesk.Revit.DB.Lighting',
'Autodesk.Revit.DB.Macros',
'Autodesk.Revit.DB.Mechanical',
'Autodesk.Revit.DB.Plumbing',
'Autodesk.Revit.DB.PointClouds',
'Autodesk.Revit.DB.Structure',
'Autodesk.Revit.DB.Structure.StructuralSections',

'Autodesk.Revit.UI',
'Autodesk.Revit.UI.Events',
'Autodesk.Revit.UI.Macros',
'Autodesk.Revit.UI.Mechanical',
'Autodesk.Revit.UI.Plumbing',
'Autodesk.Revit.UI.Selection',

'RevitServices.Persistence',
'RevitServices.Transactions',
	
'Revit.Application',
'Revit.Elements',
'Revit.Elements.Views',
'Revit.Filter',
'Revit.GeometryConversion',
'Revit.GeometryObjects',
'Revit.Transaction',
'Revit.References',
'Revit.AnalysisDisplay',

'System',
'System.Boolean',
'System.Collections',
'System.Collections.Generic',
'System.IO',
'System.String',
'System.Treading']

for i in list(modules):
    generator3.process_one(i, None, True, path)</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>